name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_x64:
    name: 'Build x64'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b #pin v5.4.0
        with:
          go-version: 'stable'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Package
        run: ./build.sh $(git describe)
      
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: configsync_x64
          path: |
            artifacts/configsync-*_darwin-amd64.tar.gz
            artifacts/configsync-*_freebsd-amd64.tar.gz
            artifacts/configsync-*_linux-amd64.tar.gz
            artifacts/configsync-*_netbsd-amd64.tar.gz
            artifacts/configsync-*_openbsd-amd64.tar.gz
            artifacts/configsync-*-1.x86_64.rpm
            artifacts/configsync-*.amd64.deb
          compression-level: 0

  build_arm64:
    name: 'Build arm64'
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b #pin v5.4.0
        with:
          go-version: 'stable'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Package
        run: ./build.sh $(git describe)

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: configsync_arm64
          path: |
            artifacts/configsync-*_darwin-arm64.tar.gz
            artifacts/configsync-*_freebsd-arm64.tar.gz
            artifacts/configsync-*_linux-arm64.tar.gz
            artifacts/configsync-*_netbsd-arm64.tar.gz
            artifacts/configsync-*_openbsd-arm64.tar.gz
            artifacts/configsync-*-1.aarch64.rpm
            artifacts/configsync-*.arm64.deb
          compression-level: 0
